### ISSUE TITLE
Caching Problem

### ISSUE THREAD

**Issue by michi-z** [clivewalkden/Magento2_JivoChat#5]
The module is making all pages not cacheable. 

It's in the layout file: 'public/vendor/sozodesign/magento2-jivochat/view/frontend/layout/default.xml -> cacheable="false"'

Is the 'cacheable' argument necessary?

**Comment by clivewalkden** [comment]
Hi @michi-z,

The cacheable="false" only makes that block un-cachable not the pages it appears on. What version of Magento are you running on?

**Comment by michi-z** [comment]
He Clive, look hier https://maxchadwick.xyz/blog/how-magento-2-decides-if-a-page-is-cacheable. Especially 'As you can see, after build-ing the layout XML, the method checks if the final resulting layout XML contains any blocks with the cacheable attribute set to false. If it finds any, the entire response will not be cached.'
We are running the version 2.2.6

**Comment by clivewalkden** [comment]
Thanks for the info. This will be updated before the end of the week.

**Comment by michi-z** [comment]
When will it be updated?

**Comment by clivewalkden** [comment]
Apologies for the delay, I've just pushed version 1.0.4 which should fix the issue
